name: Close Snaps

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  close:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - name: Close obsolete channels
      uses: canonical/actions/close-snap@369aa83db4b62bdf1cb4240f651f11f0eb9fac11
      continue-on-error: true
      with:
        channel: edge/pr${{ github.event.number }}
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
